#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

resourcesDir=/home/g.zhdanko/openFOAM/resources

restore0Dir

# cp -rf "$resourcesDir"/meshes/naca0012/polyMesh/ constant/
touch naca0012_reference.foam
runApplication decomposePar

runParallel $(getApplication)

#------------------------------------------------------------------------------
